// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIA4iRgmt9JxGgwSqMwP9vhgZ4C_rAONk',
    appId: '1:272380051626:web:f466168dbd48eed68d90d3',
    messagingSenderId: '272380051626',
    projectId: 'twitter-clone-b42ed',
    authDomain: 'twitter-clone-b42ed.firebaseapp.com',
    storageBucket: 'twitter-clone-b42ed.appspot.com',
    measurementId: 'G-M7T83XTQD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Gz5pPvpyqi3XJGwlKHuOX6I6-1XQfDs',
    appId: '1:272380051626:android:ccc82c477a12db6d8d90d3',
    messagingSenderId: '272380051626',
    projectId: 'twitter-clone-b42ed',
    storageBucket: 'twitter-clone-b42ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9zYxf0kWQ1Un3s1yqIgygCvk2qhW7FU8',
    appId: '1:272380051626:ios:73369c314921e0d58d90d3',
    messagingSenderId: '272380051626',
    projectId: 'twitter-clone-b42ed',
    storageBucket: 'twitter-clone-b42ed.appspot.com',
    iosClientId: '272380051626-9rfn1qlh8ghrdb1bvfn6fg019ibo15f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9zYxf0kWQ1Un3s1yqIgygCvk2qhW7FU8',
    appId: '1:272380051626:ios:690bd410543ea94e8d90d3',
    messagingSenderId: '272380051626',
    projectId: 'twitter-clone-b42ed',
    storageBucket: 'twitter-clone-b42ed.appspot.com',
    iosClientId: '272380051626-4q1grqi1500tnasb4bns02nmvrhacijo.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
